# start the zookeeper first

services:
  kafka-zookeeper:
    image: zookeeper
    ports:
      - 2181:2181 #zookeeper client port
  
  kafka:
    image: confluentinc/cp-kafka
    hostname: localhost # otherwise the connection was failing from the client while connecting to KAFKA_ADVERTISED_LISTENERS
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - kafka-zookeeper